CREATE TABLE smtp_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  host VARCHAR(255) NOT NULL,
  port INT NOT NULL DEFAULT 587,
  secure VARCHAR(10) NOT NULL DEFAULT 'tls',
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  from_email VARCHAR(255) NOT NULL,
  from_name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1
);
